version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ticket-redis
    ports:
      - "6379:6379"
    # Ovo uključuje Redis keyspace notifikacije za expired događaje
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ticket-rabbitmq
    ports:
      - "5672:5672"    # AMQP protokol
      - "15672:15672"  # Management UI (otvori http://localhost:15672 guest/guest)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s

  event-db:
    image: postgres:16-alpine
    container_name: event-db
    environment:
      POSTGRES_DB: event_db
      POSTGRES_USER: event_user
      POSTGRES_PASSWORD: event_pass
    ports:
      - "5433:5432"
    volumes:
      - event-db-data:/var/lib/postgresql/data

  booking-db:
    image: postgres:16-alpine
    container_name: booking-db
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
    ports:
      - "5434:5432"
    volumes:
      - booking-db-data:/var/lib/postgresql/data

  notification-db:
    image: postgres:16-alpine
    container_name: notification-db
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: notification_pass
    ports:
      - "5435:5432"
    volumes:
      - notification-db-data:/var/lib/postgresql/data

volumes:
  event-db-data:
  booking-db-data:
  notification-db-data: