spring.application.name=event-inventory-service
server.port=8083

# PostgreSQL baza (event_db)
spring.datasource.url=jdbc:postgresql://localhost:5433/event_db
spring.datasource.username=event_user
spring.datasource.password=event_pass
spring.jpa.hibernate.ddl-auto=update

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379